// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Titles {
	
	
	public partial class auth {
		
		protected System.Web.UI.HtmlControls.HtmlForm addForm;
		
		protected System.Web.UI.WebControls.TextBox firstName;
		
		protected System.Web.UI.WebControls.TextBox lastName;
		
		protected System.Web.UI.WebControls.TextBox position;
		
		protected System.Web.UI.WebControls.Button submitButton;
	}
}
